unit fu_config;
{
Copyright (C) 2002 Patrick Chevalley

http://www.astrosurf.com/astropc
pch@freesurf.ch

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
}
{
 Configuration form for Linux CLX application
}
interface

uses Math, enhedits, u_constant, u_util,
  SysUtils, Classes, QForms,Types,
  QStdCtrls, QComCtrls, QControls, QGraphics, QExtCtrls, QGrids, QButtons,
  QDialogs, QMask, QCheckLst;

type
  Tf_config = class(TForm)
    PageControl1: TPageControl;
    p_catgen: TTabSheet;
    Label1: TLabel;
    p_cdcstars: TTabSheet;
    p_cdcneb: TTabSheet;
    p_external: TTabSheet;
    Label2: TLabel;
    Label3: TLabel;
    Label4: TLabel;
    p_planets: TTabSheet;
    p_comets: TTabSheet;
    p_asteroids: TTabSheet;
    p_color: TTabSheet;
    p_lines: TTabSheet;
    p_labels: TTabSheet;
    Label5: TLabel;
    Label6: TLabel;
    Label7: TLabel;
    Label8: TLabel;
    Label9: TLabel;
    Label10: TLabel;
    p_catalog: TTabSheet;
    Label11: TLabel;
    p_solsys: TTabSheet;
    Label12: TLabel;
    p_cdc: TTabSheet;
    p_display: TTabSheet;
    Label14: TLabel;
    Label65: TLabel;
    BSCbox: TCheckBox;
    Fbsc1: TLongEdit;
    Fbsc2: TLongEdit;
    bsc3: TEdit;
    BitBtn9: TBitBtn;
    Label66: TLabel;
    SKYbox: TCheckBox;
    Fsky1: TLongEdit;
    Fsky2: TLongEdit;
    sky3: TEdit;
    BitBtn10: TBitBtn;
    BitBtn11: TBitBtn;
    tyc3: TEdit;
    Ftyc2: TLongEdit;
    Ftyc1: TLongEdit;
    TYCbox: TCheckBox;
    Label67: TLabel;
    Label87: TLabel;
    TY2Box: TCheckBox;
    TICbox: TCheckBox;
    Ftic1: TLongEdit;
    Fty21: TLongEdit;
    Fty22: TLongEdit;
    Ftic2: TLongEdit;
    ty23: TEdit;
    tic3: TEdit;
    BitBtn13: TBitBtn;
    BitBtn12: TBitBtn;
    GSCFBox: TCheckBox;
    GSCCbox: TCheckBox;
    GSCbox: TCheckBox;
    USNbox: TCheckBox;
    MCTBox: TCheckBox;
    dsbasebox: TCheckBox;
    dstycBox: TCheckBox;
    dsgscBox: TCheckBox;
    USNBright: TCheckBox;
    fgscf1: TLongEdit;
    fgscc1: TLongEdit;
    fgsc1: TLongEdit;
    fusn1: TLongEdit;
    fmct1: TLongEdit;
    dsbase1: TLongEdit;
    dstyc1: TLongEdit;
    dsgsc1: TLongEdit;
    dsgsc2: TLongEdit;
    dstyc2: TLongEdit;
    dsbase2: TLongEdit;
    fmct2: TLongEdit;
    fusn2: TLongEdit;
    fgsc2: TLongEdit;
    fgscc2: TLongEdit;
    fgscf2: TLongEdit;
    gscf3: TEdit;
    gscc3: TEdit;
    gsc3: TEdit;
    usn3: TEdit;
    mct3: TEdit;
    dsbase3: TEdit;
    dstyc3: TEdit;
    dsgsc3: TEdit;
    BitBtn22: TBitBtn;
    BitBtn21: TBitBtn;
    BitBtn20: TBitBtn;
    BitBtn32: TBitBtn;
    BitBtn19: TBitBtn;
    BitBtn18: TBitBtn;
    BitBtn17: TBitBtn;
    BitBtn16: TBitBtn;
    Label16: TLabel;
    Label28: TLabel;
    Label17: TLabel;
    Label27: TLabel;
    Label18: TLabel;
    Label21: TLabel;
    BitBtn14: TBitBtn;
    BitBtn15: TBitBtn;
    wds3: TEdit;
    gcv3: TEdit;
    Fgcv2: TLongEdit;
    Fwds2: TLongEdit;
    Fwds1: TLongEdit;
    Fgcv1: TLongEdit;
    GCVBox: TCheckBox;
    IRVar: TCheckBox;
    WDSbox: TCheckBox;
    Label19: TLabel;
    Label20: TLabel;
    Label22: TLabel;
    Label23: TLabel;
    Label24: TLabel;
    Label25: TLabel;
    Label26: TLabel;
    Label69: TLabel;
    NGCbox: TCheckBox;
    RC3box: TCheckBox;
    OCLbox: TCheckBox;
    GCMbox: TCheckBox;
    GPNbox: TCheckBox;
    LBNbox: TCheckBox;
    ngc3: TEdit;
    rc33: TEdit;
    lbn3: TEdit;
    ocl3: TEdit;
    gcm3: TEdit;
    gpn3: TEdit;
    PGCBox: TCheckBox;
    pgc3: TEdit;
    SACbox: TCheckBox;
    sac3: TEdit;
    fngc1: TLongEdit;
    fngc2: TLongEdit;
    fsac1: TLongEdit;
    fsac2: TLongEdit;
    flbn1: TLongEdit;
    flbn2: TLongEdit;
    frc31: TLongEdit;
    frc32: TLongEdit;
    fpgc1: TLongEdit;
    fpgc2: TLongEdit;
    focl1: TLongEdit;
    focl2: TLongEdit;
    fgcm1: TLongEdit;
    fgcm2: TLongEdit;
    fgpn1: TLongEdit;
    fgpn2: TLongEdit;
    BitBtn23: TBitBtn;
    BitBtn24: TBitBtn;
    BitBtn25: TBitBtn;
    BitBtn26: TBitBtn;
    BitBtn27: TBitBtn;
    BitBtn28: TBitBtn;
    BitBtn29: TBitBtn;
    BitBtn30: TBitBtn;
    Label52: TLabel;
    Label71: TLabel;
    StringGrid1: TStringGrid;
    Cat1Box: TCheckBox;
    Edit1: TEdit;
    Label64: TLabel;
    Cat2Box: TCheckBox;
    StringGrid2: TStringGrid;
    Label37: TLabel;
    BitBtn33: TBitBtn;
    BitBtn35: TBitBtn;
    StringGrid3: TStringGrid;
    p_chart: TTabSheet;
    p_fov: TTabSheet;
    p_filter: TTabSheet;
    Label29: TLabel;
    Label30: TLabel;
    GroupBox2: TGroupBox;
    StarBox: TCheckBox;
    GroupBox1: TGroupBox;
    NebBox: TCheckBox;
    BigNebBox: TCheckBox;
    p_image: TTabSheet;
    Label89: TLabel;
    PlanetBox: TCheckBox;
    PlanetMode: TRadioGroup;
    PlanetBox2: TCheckBox;
    PlanetBox3: TCheckBox;
    GRS: TFloatEdit;
    BitBtn37: TBitBtn;
    Panel4: TPanel;
    Panel3: TPanel;
    Label110: TLabel;
    fsmagvis: TFloatEdit;
    StarAutoBox: TCheckBox;
    Panel2: TPanel;
    Label32: TLabel;
    Label33: TLabel;
    Label34: TLabel;
    Label35: TLabel;
    Label36: TLabel;
    Label38: TLabel;
    Label39: TLabel;
    Label40: TLabel;
    Label76: TLabel;
    Label78: TLabel;
    Label108: TLabel;
    Label109: TLabel;
    fsmag0: TFloatEdit;
    fsmag1: TFloatEdit;
    fsmag2: TFloatEdit;
    fsmag3: TFloatEdit;
    fsmag4: TFloatEdit;
    fsmag5: TFloatEdit;
    fsmag6: TFloatEdit;
    fsmag7: TFloatEdit;
    fsmag8: TFloatEdit;
    fsmag9: TFloatEdit;
    Panel5: TPanel;
    fmag0: TFloatEdit;
    fmag1: TFloatEdit;
    fmag2: TFloatEdit;
    fmag3: TFloatEdit;
    fmag4: TFloatEdit;
    fmag5: TFloatEdit;
    fmag6: TFloatEdit;
    fdim0: TFloatEdit;
    fdim1: TFloatEdit;
    fdim2: TFloatEdit;
    fdim3: TFloatEdit;
    fdim4: TFloatEdit;
    fdim5: TFloatEdit;
    fdim6: TFloatEdit;
    Label48: TLabel;
    Label49: TLabel;
    Label41: TLabel;
    Label42: TLabel;
    Label43: TLabel;
    Label44: TLabel;
    Label45: TLabel;
    Label46: TLabel;
    Label47: TLabel;
    Label79: TLabel;
    Label80: TLabel;
    Label111: TLabel;
    Label112: TLabel;
    fmag7: TFloatEdit;
    fmag8: TFloatEdit;
    fmag9: TFloatEdit;
    fdim7: TFloatEdit;
    fdim8: TFloatEdit;
    fdim9: TFloatEdit;
    CancelBtn: TButton;
    OKBtn: TButton;
    HelpBtn: TButton;
    Label15: TLabel;
    Label116: TLabel;
    Label117: TLabel;
    Label118: TLabel;
    Label119: TLabel;
    Bevel3: TBevel;
    Bevel4: TBevel;
    Bevel5: TBevel;
    Label120: TLabel;
    p_fonts: TTabSheet;
    Label51: TLabel;
    Label121: TLabel;
    Label122: TLabel;
    Label123: TLabel;
    Label124: TLabel;
    Label125: TLabel;
    Label126: TLabel;
    Label127: TLabel;
    Label128: TLabel;
    Label129: TLabel;
    gridfont: TEdit;
    labelfont: TEdit;
    legendfont: TEdit;
    statusfont: TEdit;
    listfont: TEdit;
    prtfont: TEdit;
    FontDialog1: TFontDialog;
    SpeedButton1: TSpeedButton;
    SpeedButton2: TSpeedButton;
    SpeedButton3: TSpeedButton;
    SpeedButton4: TSpeedButton;
    SpeedButton5: TSpeedButton;
    SpeedButton6: TSpeedButton;
    Button1: TButton;
    stardisplay: TRadioGroup;
    nebuladisplay: TRadioGroup;
    Applyall: TCheckBox;
    TreeView1: TTreeView;
    p_time: TTabSheet;
    p_simulation: TTabSheet;
    Label50: TLabel;
    Label72: TLabel;
    Panel11: TPanel;
    Label73: TLabel;
    Label74: TLabel;
    Label75: TLabel;
    LabelDate: TLabel;
    LabelTime: TLabel;
    LabelTimezone: TLabel;
    CheckBox1: TCheckBox;
    CheckBox2: TCheckBox;
    Panel7: TPanel;
    Label131: TLabel;
    Label132: TLabel;
    Label133: TLabel;
    tz: TFloatEdit;
    Panel12: TPanel;
    Label146: TLabel;
    Tdt_Ut: TLabel;
    Label152: TLabel;
    Label153: TLabel;
    CheckBox4: TCheckBox;
    dt_ut: TLongEdit;
    Panel9: TPanel;
    Label154: TLabel;
    Label158: TLabel;
    Label159: TLabel;
    Label160: TLabel;
    Label161: TLabel;
    Label162: TLabel;
    Label163: TLabel;
    Label164: TLabel;
    BitBtn4: TBitBtn;
    ADBC: TRadioGroup;
    d_year: TSpinEdit;
    d_month: TSpinEdit;
    d_day: TSpinEdit;
    t_hour: TSpinEdit;
    t_min: TSpinEdit;
    t_sec: TSpinEdit;
    LongEdit2: TLongEdit;
    previous: TButton;
    next: TButton;
    Label165: TLabel;
    Label31: TLabel;
    Panel1: TPanel;
    Label134: TLabel;
    Label135: TLabel;
    PMBox: TCheckBox;
    DrawPmBox: TCheckBox;
    lDrawPMy: TLongEdit;
    Panel10: TPanel;
    Label136: TLabel;
    Labelequinox: TLabel;
    equinoxtype: TRadioGroup;
    equinox2: TFloatEdit;
    equinox1: TComboBox;
    projectiontype: TRadioGroup;
    Label96: TLabel;
    Label97: TLabel;
    Label98: TLabel;
    Label99: TLabel;
    Label100: TLabel;
    Label101: TLabel;
    Label102: TLabel;
    Label103: TLabel;
    Label104: TLabel;
    Label105: TLabel;
    Label106: TLabel;
    Label107: TLabel;
    Label114: TLabel;
    fw1: TFloatEdit;
    fw2: TFloatEdit;
    fw3: TFloatEdit;
    fw4: TFloatEdit;
    fw5: TFloatEdit;
    fw6: TFloatEdit;
    fw7: TFloatEdit;
    fw8: TFloatEdit;
    fw9: TFloatEdit;
    fw10: TFloatEdit;
    fw0: TFloatEdit;
    fw00: TFloatEdit;
    Label138: TLabel;
    Label139: TLabel;
    fBigNebLimit: TLongEdit;
    Label140: TLabel;
    Label13: TLabel;
    Label68: TLabel;
    Label113: TLabel;
    p_projection: TTabSheet;
    Label77: TLabel;
    Labelp1: TLabel;
    Labelp2: TLabel;
    Labelp3: TLabel;
    Labelp4: TLabel;
    Label149: TLabel;
    Labelp0: TLabel;
    Labelp5: TLabel;
    Labelp6: TLabel;
    Labelp7: TLabel;
    Labelp8: TLabel;
    Labelp9: TLabel;
    Labelp10: TLabel;
    Label171: TLabel;
    Label172: TLabel;
    Label173: TLabel;
    ComboBox2: TComboBox;
    ComboBox1: TComboBox;
    ComboBox3: TComboBox;
    ComboBox4: TComboBox;
    ComboBox5: TComboBox;
    ComboBox6: TComboBox;
    ComboBox7: TComboBox;
    ComboBox8: TComboBox;
    ComboBox9: TComboBox;
    ComboBox10: TComboBox;
    OpenDialog1: TOpenDialog;
    ComboBox11: TComboBox;
    p_gridspacing: TTabSheet;
    Label115: TLabel;
    Label130: TLabel;
    Label137: TLabel;
    Label147: TLabel;
    Label148: TLabel;
    Label150: TLabel;
    Label151: TLabel;
    Label155: TLabel;
    Label156: TLabel;
    Label157: TLabel;
    Label169: TLabel;
    Label170: TLabel;
    Label174: TLabel;
    Label175: TLabel;
    Label176: TLabel;
    MaskEdit1: TMaskEdit;
    MaskEdit2: TMaskEdit;
    MaskEdit3: TMaskEdit;
    MaskEdit4: TMaskEdit;
    MaskEdit5: TMaskEdit;
    MaskEdit6: TMaskEdit;
    MaskEdit7: TMaskEdit;
    MaskEdit8: TMaskEdit;
    MaskEdit9: TMaskEdit;
    MaskEdit10: TMaskEdit;
    MaskEdit11: TMaskEdit;
    MaskEdit12: TMaskEdit;
    MaskEdit13: TMaskEdit;
    MaskEdit14: TMaskEdit;
    MaskEdit15: TMaskEdit;
    MaskEdit16: TMaskEdit;
    MaskEdit17: TMaskEdit;
    MaskEdit18: TMaskEdit;
    MaskEdit19: TMaskEdit;
    MaskEdit20: TMaskEdit;
    MaskEdit21: TMaskEdit;
    MaskEdit22: TMaskEdit;
    PlaParalaxe: TRadioGroup;
    Planet3: TEdit;
    Label53: TLabel;
    BitBtn31: TBitBtn;
    Label177: TLabel;
    Edit2: TEdit;
    Button2: TButton;
    SpeedButton7: TSpeedButton;
    Label167: TLabel;
    Label168: TLabel;
    stepunit: TRadioGroup;
    stepline: TCheckBox;
    Label166: TLabel;
    nbstep: TSpinEdit;
    stepsize: TSpinEdit;
    SimObj: TCheckListBox;
    Label178: TLabel;
    ApparentType: TRadioGroup;
    Label179: TLabel;
    EqGrid: TCheckBox;
    AzGrid: TCheckBox;
    Constl: TCheckBox;
    ConstlFile: TEdit;
    Label180: TLabel;
    ConstlFileBtn: TBitBtn;
    Bevel6: TBevel;
    bg1: TPanel;
    Shape1: TShape;
    Shape2: TShape;
    Shape3: TShape;
    Shape4: TShape;
    Shape5: TShape;
    Shape6: TShape;
    Shape7: TShape;
    Label181: TLabel;
    Label182: TLabel;
    Label183: TLabel;
    Label184: TLabel;
    Label185: TLabel;
    Label186: TLabel;
    Label187: TLabel;
    Label188: TLabel;
    Label189: TLabel;
    bg2: TPanel;
    Shape8: TShape;
    Shape9: TShape;
    Shape10: TShape;
    Shape11: TShape;
    Shape12: TShape;
    Shape13: TShape;
    Label190: TLabel;
    Label191: TLabel;
    Label192: TLabel;
    Label193: TLabel;
    Label194: TLabel;
    Label195: TLabel;
    bg3: TPanel;
    Shape15: TShape;
    Shape16: TShape;
    Shape17: TShape;
    Label197: TLabel;
    Label198: TLabel;
    Label199: TLabel;
    Shape14: TShape;
    Label196: TLabel;
    DefColor: TRadioGroup;
    p_skycolor: TTabSheet;
    p_nebcolor: TTabSheet;
    Label200: TLabel;
    Label201: TLabel;
    skycolorbox: TRadioGroup;
    Panel6: TPanel;
    Shape18: TShape;
    Shape19: TShape;
    Shape20: TShape;
    Shape21: TShape;
    Shape22: TShape;
    Shape23: TShape;
    Shape24: TShape;
    Label202: TLabel;
    Label205: TLabel;
    Label208: TLabel;
    Button3: TButton;
    ColorDialog1: TColorDialog;
    procedure TreeView1Change(Sender: TObject; Node: TTreeNode);
    procedure FormCreate(Sender: TObject);
    procedure SelectFontClick(Sender: TObject);
    procedure DefaultFontClick(Sender: TObject);
    procedure FormShow(Sender: TObject);
    procedure FWChange(Sender: TObject);
    procedure CDCStarSelClick(Sender: TObject);
    procedure CDCStarField1Change(Sender: TObject);
    procedure CDCStarField2Change(Sender: TObject);
    procedure CDCStarPathChange(Sender: TObject);
    procedure CDCStarSelPathClick(Sender: TObject);
    procedure StarBoxClick(Sender: TObject);
    procedure StarAutoBoxClick(Sender: TObject);
    procedure NebBoxClick(Sender: TObject);
    procedure BigNebBoxClick(Sender: TObject);
    procedure fsmagvisChange(Sender: TObject);
    procedure fsmagChange(Sender: TObject);
    procedure fmagChange(Sender: TObject);
    procedure fdimChange(Sender: TObject);
    procedure CDCNebSelPathClick(Sender: TObject);
    procedure CDCNebSelClick(Sender: TObject);
    procedure CDCNebField1Change(Sender: TObject);
    procedure CDCNebField2Change(Sender: TObject);
    procedure CDCNebPathChange(Sender: TObject);
    procedure USNBrightClick(Sender: TObject);
    procedure IRVarClick(Sender: TObject);
    procedure GCVBoxClick(Sender: TObject);
    procedure Fgcv1Change(Sender: TObject);
    procedure Fgcv2Change(Sender: TObject);
    procedure WDSboxClick(Sender: TObject);
    procedure Fwds1Change(Sender: TObject);
    procedure Fwds2Change(Sender: TObject);
    procedure gcv3Change(Sender: TObject);
    procedure wds3Change(Sender: TObject);
    procedure BitBtn14Click(Sender: TObject);
    procedure BitBtn15Click(Sender: TObject);
    procedure stardisplayClick(Sender: TObject);
    procedure nebuladisplayClick(Sender: TObject);
    procedure nextClick(Sender: TObject);
    procedure previousClick(Sender: TObject);
    procedure CheckBox1Click(Sender: TObject);
    procedure CheckBox2Click(Sender: TObject);
    procedure LongEdit2Change(Sender: TObject);
    procedure BitBtn4Click(Sender: TObject);
    procedure tzChange(Sender: TObject);
    procedure CheckBox4Click(Sender: TObject);
    procedure dt_utChange(Sender: TObject);
    procedure fBigNebLimitChange(Sender: TObject);
    procedure StringGrid3DrawCell(Sender: TObject; ACol, ARow: Integer;
      Rect: TRect; State: TGridDrawState);
    procedure StringGrid3MouseUp(Sender: TObject; Button: TMouseButton;
      Shift: TShiftState; X, Y: Integer);
    procedure StringGrid3SelectCell(Sender: TObject; ACol, ARow: Integer;
      var CanSelect: Boolean);
    procedure StringGrid3SetEditText(Sender: TObject; ACol, ARow: Integer;
      const Value: WideString);
    procedure BitBtn33Click(Sender: TObject);
    procedure BitBtn35Click(Sender: TObject);
    procedure FormClose(Sender: TObject; var Action: TCloseAction);
    procedure equinoxtypeClick(Sender: TObject);
    procedure equinox1Change(Sender: TObject);
    procedure equinox2Change(Sender: TObject);
    procedure PMBoxClick(Sender: TObject);
    procedure DrawPmBoxClick(Sender: TObject);
    procedure lDrawPMyChange(Sender: TObject);
    procedure ProjectionChange(Sender: TObject);
    procedure TimeChange(Sender: TObject; NewValue: Integer);
    procedure DateChange(Sender: TObject; NewValue: Integer);
    procedure DateChange2(Sender: TObject);
    procedure TimeChange2(Sender: TObject);
    procedure DegSpacingChange(Sender: TObject);
    procedure HourSpacingChange(Sender: TObject);
    procedure PlaParalaxeClick(Sender: TObject);
    procedure PlanetBoxClick(Sender: TObject);
    procedure PlanetModeClick(Sender: TObject);
    procedure GRSChange(Sender: TObject);
    procedure PlanetBox2Click(Sender: TObject);
    procedure PlanetBox3Click(Sender: TObject);
    procedure Button2Click(Sender: TObject);
    procedure nbstepChanged(Sender: TObject; NewValue: Integer);
    procedure steplineClick(Sender: TObject);
    procedure stepunitClick(Sender: TObject);
    procedure stepsizeChanged(Sender: TObject; NewValue: Integer);
    procedure SimObjClickCheck(Sender: TObject);
    procedure projectiontypeClick(Sender: TObject);
    procedure ConstlFileBtnClick(Sender: TObject);
    procedure ConstlFileChange(Sender: TObject);
    procedure EqGridClick(Sender: TObject);
    procedure AzGridClick(Sender: TObject);
    procedure ConstlClick(Sender: TObject);
    procedure ApparentTypeClick(Sender: TObject);
    procedure bgClick(Sender: TObject);
    procedure ShapeMouseUp(Sender: TObject; Button: TMouseButton;
      Shift: TShiftState; X, Y: Integer);
    procedure DefColorClick(Sender: TObject);
    procedure skycolorboxClick(Sender: TObject);
    procedure ShapeSkyMouseUp(Sender: TObject; Button: TMouseButton;
      Shift: TShiftState; X, Y: Integer);
    procedure Button3Click(Sender: TObject);
  private
    { Déclarations privées }
    procedure EditGCatPath(row : integer);
    procedure DeleteGCatRow(p : integer);
  public
    { Déclarations publiques }
    ccat : conf_catalog;
    cshr : conf_shared;
    csc  : conf_skychart;
    cplot : conf_plot;
    cmain : conf_main;
    catalogempty: boolean;
    procedure SetLang(lang:string);
    function SelectPage(txt:string):boolean;
    procedure SetFonts(ctrl:Tedit;num:integer);
    procedure ShowTime;
    procedure ShowChart;
    procedure SetEquinox;
    procedure ShowDisplay;
    procedure ShowFonts;
    procedure SetFieldHint(var lab:Tlabel; n:integer);
    procedure ShowProjection;
    procedure ShowField;
    procedure ShowPlanet;
    procedure ShowFilter;
    procedure ShowGridSpacing;
    procedure ShowGcat;
    procedure ShowCDCStar;
    procedure ShowCDCNeb;
    procedure ShowLine;
    procedure ShowColor;
    procedure ShowSkyColor;
  end;

var
  f_config: Tf_config;

implementation

uses fu_main, fu_directory, u_projection;

const b=' ';

{$R *.xfm}

// include all cross-platform common code.
// you can temporarily copy the file content here
// to use the IDE facilities

{$include i_config.pas }

// end of common code

// Specific Linux CLX code:

procedure Tf_config.nbstepChanged(Sender: TObject; NewValue: Integer);
begin
csc.Simnb:=nbstep.value;
end;

procedure Tf_config.stepsizeChanged(Sender: TObject; NewValue: Integer);
begin
stepunitClick(Sender);
end;

// End of Linux specific CLX code:

end.


