unit pu_config;
{
Copyright (C) 2002 Patrick Chevalley

http://www.astrosurf.com/astropc
pch@freesurf.ch

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
}
{
 Configuration form for Windows VCL application
}
interface

uses Math, u_constant, u_util, jpeg, pngimage, passql, pasmysql, u_projection,
  Windows, Messages, SysUtils, Variants, Classes, Graphics, Controls, Forms,
  Dialogs, ComCtrls, StdCtrls, Buttons, Grids, ExtCtrls, enhedits, ActnList,
  FoldrDlg, Spin, Mask, CheckLst, StrUtils, cu_zoomimage, cu_fits;

type
  Tf_config = class(TForm)
    TreeView1: TTreeView;
    CancelBtn: TButton;
    OKBtn: TButton;
    HelpBtn: TButton;
    FontDialog1: TFontDialog;
    FolderDialog1: TFolderDialog;
    OpenDialog1: TOpenDialog;
    Applyall: TCheckBox;
    next: TButton;
    previous: TButton;
    Apply: TButton;
    ColorDialog1: TColorDialog;
    topmsg: TPanel;
    PageControl1: TPageControl;
    s_time: TTabSheet;
    s_observatory: TTabSheet;
    pa_time: TPageControl;
    t_time: TTabSheet;
    Label142: TLabel;
    Label147: TLabel;
    CheckBox1: TCheckBox;
    CheckBox2: TCheckBox;
    Panel7: TPanel;
    Label134: TLabel;
    Label148: TLabel;
    Label149: TLabel;
    tz: TFloatEdit;
    Panel8: TPanel;
    Label135: TLabel;
    Tdt_Ut: TLabel;
    Label136: TLabel;
    Label150: TLabel;
    CheckBox4: TCheckBox;
    dt_ut: TLongEdit;
    Panel9: TPanel;
    Label137: TLabel;
    Label139: TLabel;
    Label141: TLabel;
    Label138: TLabel;
    Label143: TLabel;
    Label144: TLabel;
    Label145: TLabel;
    Label140: TLabel;
    BitBtn4: TBitBtn;
    ADBC: TRadioGroup;
    d_year: TSpinEdit;
    d_month: TSpinEdit;
    d_day: TSpinEdit;
    t_hour: TSpinEdit;
    t_min: TSpinEdit;
    t_sec: TSpinEdit;
    LongEdit2: TLongEdit;
    t_simulation: TTabSheet;
    Label146: TLabel;
    stepreset: TSpeedButton;
    Label178: TLabel;
    Label179: TLabel;
    Label180: TLabel;
    Label56: TLabel;
    stepunit: TRadioGroup;
    stepline: TCheckBox;
    nbstep: TSpinEdit;
    stepsize: TSpinEdit;
    SimObj: TCheckListBox;
    pa_observatory: TPageControl;
    t_observatory: TTabSheet;
    t_horizon: TTabSheet;
    Latitude: TGroupBox;
    Label58: TLabel;
    Label59: TLabel;
    Label60: TLabel;
    hemis: TComboBox;
    latdeg: TLongEdit;
    latmin: TLongEdit;
    latsec: TLongEdit;
    Longitude: TGroupBox;
    Label61: TLabel;
    Label62: TLabel;
    Label63: TLabel;
    long: TComboBox;
    longdeg: TLongEdit;
    longmin: TLongEdit;
    longsec: TLongEdit;
    Altitude: TGroupBox;
    Label70: TLabel;
    altmeter: TFloatEdit;
    refraction: TGroupBox;
    Label82: TLabel;
    Label83: TLabel;
    pressure: TFloatEdit;
    temperature: TFloatEdit;
    timezone: TGroupBox;
    Label81: TLabel;
    timez: TFloatEdit;
    Obszp: TButton;
    Obszm: TButton;
    Obsmap: TButton;
    ZoomImage1: TZoomImage;
    HScrollBar: TScrollBar;
    VScrollBar: TScrollBar;
    obsname: TGroupBox;
    dbreado: TPanel;
    citylist: TComboBox;
    citysearch: TButton;
    countrylist: TComboBox;
    cityfilter: TEdit;
    newcity: TButton;
    updcity: TButton;
    delcity: TButton;
    hor_l1: TLabel;
    hor_l2: TLabel;
    horizonopaque: TCheckBox;
    horizonfile: TEdit;
    horizonfileBtn: TBitBtn;
    s_chart: TTabSheet;
    pa_chart: TPageControl;
    t_chart: TTabSheet;
    t_fov: TTabSheet;
    t_projection: TTabSheet;
    t_filter: TTabSheet;
    t_grid: TTabSheet;
    t_objlist: TTabSheet;
    Label31: TLabel;
    Panel1: TPanel;
    Label68: TLabel;
    Label113: TLabel;
    PMBox: TCheckBox;
    DrawPmBox: TCheckBox;
    lDrawPMy: TLongEdit;
    Panel10: TPanel;
    Label151: TLabel;
    Label152: TLabel;
    equinoxtype: TRadioGroup;
    equinox2: TFloatEdit;
    equinox1: TComboBox;
    projectiontype: TRadioGroup;
    ApparentType: TRadioGroup;
    Label30: TLabel;
    Bevel1: TBevel;
    Bevel2: TBevel;
    Label96: TLabel;
    Label97: TLabel;
    Label98: TLabel;
    Label99: TLabel;
    Label100: TLabel;
    Label101: TLabel;
    Label102: TLabel;
    Label103: TLabel;
    Label104: TLabel;
    Label105: TLabel;
    Label106: TLabel;
    Label107: TLabel;
    Label114: TLabel;
    Label57: TLabel;
    Label73: TLabel;
    Label74: TLabel;
    fw1: TFloatEdit;
    fw2: TFloatEdit;
    fw3: TFloatEdit;
    fw4: TFloatEdit;
    fw5: TFloatEdit;
    fw6: TFloatEdit;
    fw7: TFloatEdit;
    fw8: TFloatEdit;
    fw9: TFloatEdit;
    fw10: TFloatEdit;
    fw0: TFloatEdit;
    fw00: TFloatEdit;
    fw4b: TFloatEdit;
    fw5b: TFloatEdit;
    Bevel8: TBevel;
    Bevel7: TBevel;
    Label158: TLabel;
    Labelp1: TLabel;
    Labelp2: TLabel;
    Labelp3: TLabel;
    Labelp4: TLabel;
    Label165: TLabel;
    Labelp0: TLabel;
    Labelp5: TLabel;
    Labelp6: TLabel;
    Labelp7: TLabel;
    Labelp8: TLabel;
    Labelp9: TLabel;
    Labelp10: TLabel;
    Label171: TLabel;
    Label172: TLabel;
    Label173: TLabel;
    ComboBox2: TComboBox;
    ComboBox1: TComboBox;
    ComboBox3: TComboBox;
    ComboBox4: TComboBox;
    ComboBox5: TComboBox;
    ComboBox6: TComboBox;
    ComboBox7: TComboBox;
    ComboBox8: TComboBox;
    ComboBox9: TComboBox;
    ComboBox10: TComboBox;
    ComboBox11: TComboBox;
    Label29: TLabel;
    GroupBox2: TGroupBox;
    StarBox: TCheckBox;
    Panel4: TPanel;
    Panel2: TPanel;
    Label32: TLabel;
    Label33: TLabel;
    Label34: TLabel;
    Label35: TLabel;
    Label36: TLabel;
    Label38: TLabel;
    Label39: TLabel;
    Label40: TLabel;
    Label76: TLabel;
    Label78: TLabel;
    Label108: TLabel;
    Label109: TLabel;
    fsmag0: TFloatEdit;
    fsmag1: TFloatEdit;
    fsmag2: TFloatEdit;
    fsmag3: TFloatEdit;
    fsmag4: TFloatEdit;
    fsmag5: TFloatEdit;
    fsmag6: TFloatEdit;
    fsmag7: TFloatEdit;
    fsmag8: TFloatEdit;
    fsmag9: TFloatEdit;
    Panel3: TPanel;
    Label110: TLabel;
    fsmagvis: TFloatEdit;
    StarAutoBox: TCheckBox;
    GroupBox1: TGroupBox;
    Label115: TLabel;
    NebBox: TCheckBox;
    BigNebBox: TCheckBox;
    Panel5: TPanel;
    Label48: TLabel;
    Label49: TLabel;
    Label41: TLabel;
    Label42: TLabel;
    Label43: TLabel;
    Label44: TLabel;
    Label45: TLabel;
    Label46: TLabel;
    Label47: TLabel;
    Label79: TLabel;
    Label80: TLabel;
    Label111: TLabel;
    Label112: TLabel;
    fmag0: TFloatEdit;
    fmag1: TFloatEdit;
    fmag2: TFloatEdit;
    fmag3: TFloatEdit;
    fmag4: TFloatEdit;
    fmag5: TFloatEdit;
    fmag6: TFloatEdit;
    fdim0: TFloatEdit;
    fdim1: TFloatEdit;
    fdim2: TFloatEdit;
    fdim3: TFloatEdit;
    fdim4: TFloatEdit;
    fdim5: TFloatEdit;
    fdim6: TFloatEdit;
    fmag7: TFloatEdit;
    fmag8: TFloatEdit;
    fmag9: TFloatEdit;
    fdim7: TFloatEdit;
    fdim8: TFloatEdit;
    fdim9: TFloatEdit;
    fBigNebLimit: TLongEdit;
    Bevel9: TBevel;
    Label159: TLabel;
    Label160: TLabel;
    Label176: TLabel;
    Label175: TLabel;
    Label161: TLabel;
    Label162: TLabel;
    Label163: TLabel;
    Label164: TLabel;
    Label166: TLabel;
    Label167: TLabel;
    Label168: TLabel;
    Label169: TLabel;
    Label170: TLabel;
    Label174: TLabel;
    Label177: TLabel;
    MaskEdit1: TMaskEdit;
    MaskEdit2: TMaskEdit;
    MaskEdit3: TMaskEdit;
    MaskEdit4: TMaskEdit;
    MaskEdit5: TMaskEdit;
    MaskEdit6: TMaskEdit;
    MaskEdit7: TMaskEdit;
    MaskEdit8: TMaskEdit;
    MaskEdit9: TMaskEdit;
    MaskEdit10: TMaskEdit;
    MaskEdit11: TMaskEdit;
    MaskEdit12: TMaskEdit;
    MaskEdit13: TMaskEdit;
    MaskEdit14: TMaskEdit;
    MaskEdit15: TMaskEdit;
    MaskEdit16: TMaskEdit;
    MaskEdit17: TMaskEdit;
    MaskEdit18: TMaskEdit;
    MaskEdit19: TMaskEdit;
    MaskEdit20: TMaskEdit;
    MaskEdit21: TMaskEdit;
    MaskEdit22: TMaskEdit;
    Label95: TLabel;
    GroupBox5: TGroupBox;
    liststar: TCheckBox;
    listneb: TCheckBox;
    listpla: TCheckBox;
    listvar: TCheckBox;
    listdbl: TCheckBox;
    s_catalog: TTabSheet;
    pa_catalog: TPageControl;
    t_catalog: TTabSheet;
    t_cdcstar: TTabSheet;
    t_cdcneb: TTabSheet;
    t_cdcobsolete: TTabSheet;
    t_cdcexternal: TTabSheet;
    Label1: TLabel;
    Label37: TLabel;
    addcat: TBitBtn;
    delcat: TBitBtn;
    StringGrid3: TStringGrid;
    Label2: TLabel;
    Label65: TLabel;
    Label66: TLabel;
    Label87: TLabel;
    Label16: TLabel;
    Label28: TLabel;
    Label17: TLabel;
    Label27: TLabel;
    Label18: TLabel;
    Label21: TLabel;
    Label19: TLabel;
    Label20: TLabel;
    BSCbox: TCheckBox;
    Fbsc1: TLongEdit;
    Fbsc2: TLongEdit;
    bsc3: TEdit;
    BitBtn9: TBitBtn;
    SKYbox: TCheckBox;
    Fsky1: TLongEdit;
    Fsky2: TLongEdit;
    sky3: TEdit;
    BitBtn10: TBitBtn;
    TY2Box: TCheckBox;
    Fty21: TLongEdit;
    Fty22: TLongEdit;
    ty23: TEdit;
    BitBtn12: TBitBtn;
    GSCFBox: TCheckBox;
    GSCCbox: TCheckBox;
    USNbox: TCheckBox;
    dsbasebox: TCheckBox;
    dstycBox: TCheckBox;
    dsgscBox: TCheckBox;
    USNBright: TCheckBox;
    fgscf1: TLongEdit;
    fgscc1: TLongEdit;
    fusn1: TLongEdit;
    dsbase1: TLongEdit;
    dstyc1: TLongEdit;
    dsgsc1: TLongEdit;
    dsgsc2: TLongEdit;
    dstyc2: TLongEdit;
    dsbase2: TLongEdit;
    fusn2: TLongEdit;
    fgscc2: TLongEdit;
    fgscf2: TLongEdit;
    gscf3: TEdit;
    gscc3: TEdit;
    usn3: TEdit;
    dsbase3: TEdit;
    dstyc3: TEdit;
    dsgsc3: TEdit;
    BitBtn22: TBitBtn;
    BitBtn21: TBitBtn;
    BitBtn20: TBitBtn;
    BitBtn19: TBitBtn;
    BitBtn17: TBitBtn;
    BitBtn16: TBitBtn;
    BitBtn14: TBitBtn;
    BitBtn15: TBitBtn;
    wds3: TEdit;
    gcv3: TEdit;
    Fgcv2: TLongEdit;
    Fwds2: TLongEdit;
    Fwds1: TLongEdit;
    Fgcv1: TLongEdit;
    GCVBox: TCheckBox;
    IRVar: TCheckBox;
    WDSbox: TCheckBox;
    Label88: TLabel;
    Label67: TLabel;
    Label91: TLabel;
    Label92: TLabel;
    Label93: TLabel;
    Label94: TLabel;
    Label90: TLabel;
    TYCbox: TCheckBox;
    Ftyc1: TLongEdit;
    Ftyc2: TLongEdit;
    tyc3: TEdit;
    BitBtn11: TBitBtn;
    TICbox: TCheckBox;
    Ftic1: TLongEdit;
    Ftic2: TLongEdit;
    tic3: TEdit;
    BitBtn13: TBitBtn;
    GSCbox: TCheckBox;
    fgsc1: TLongEdit;
    fgsc2: TLongEdit;
    gsc3: TEdit;
    BitBtn18: TBitBtn;
    MCTBox: TCheckBox;
    fmct1: TLongEdit;
    fmct2: TLongEdit;
    mct3: TEdit;
    BitBtn32: TBitBtn;
    Bevel5: TBevel;
    Bevel3: TBevel;
    Bevel4: TBevel;
    Label3: TLabel;
    Label22: TLabel;
    Label23: TLabel;
    Label24: TLabel;
    Label25: TLabel;
    Label26: TLabel;
    Label69: TLabel;
    Label15: TLabel;
    Label116: TLabel;
    Label117: TLabel;
    Label118: TLabel;
    Label119: TLabel;
    Label120: TLabel;
    NGCbox: TCheckBox;
    RC3box: TCheckBox;
    OCLbox: TCheckBox;
    GCMbox: TCheckBox;
    GPNbox: TCheckBox;
    LBNbox: TCheckBox;
    ngc3: TEdit;
    rc33: TEdit;
    lbn3: TEdit;
    ocl3: TEdit;
    gcm3: TEdit;
    gpn3: TEdit;
    PGCBox: TCheckBox;
    pgc3: TEdit;
    SACbox: TCheckBox;
    sac3: TEdit;
    fngc1: TLongEdit;
    fngc2: TLongEdit;
    fsac1: TLongEdit;
    fsac2: TLongEdit;
    flbn1: TLongEdit;
    flbn2: TLongEdit;
    frc31: TLongEdit;
    frc32: TLongEdit;
    fpgc1: TLongEdit;
    fpgc2: TLongEdit;
    focl1: TLongEdit;
    focl2: TLongEdit;
    fgcm1: TLongEdit;
    fgcm2: TLongEdit;
    fgpn1: TLongEdit;
    fgpn2: TLongEdit;
    BitBtn23: TBitBtn;
    BitBtn24: TBitBtn;
    BitBtn25: TBitBtn;
    BitBtn26: TBitBtn;
    BitBtn27: TBitBtn;
    BitBtn28: TBitBtn;
    BitBtn29: TBitBtn;
    BitBtn30: TBitBtn;
    Label4: TLabel;
    Label52: TLabel;
    Label71: TLabel;
    Label64: TLabel;
    StringGrid1: TStringGrid;
    Cat1Box: TCheckBox;
    Edit1: TEdit;
    Cat2Box: TCheckBox;
    StringGrid2: TStringGrid;
    s_solsys: TTabSheet;
    pa_solsys: TPageControl;
    t_solsys: TTabSheet;
    t_planet: TTabSheet;
    t_comet: TTabSheet;
    t_asteroid: TTabSheet;
    Label12: TLabel;
    Label131: TLabel;
    PlaParalaxe: TRadioGroup;
    planetdir: TEdit;
    planetdirsel: TBitBtn;
    Label5: TLabel;
    Label89: TLabel;
    Label53: TLabel;
    PlanetBox: TCheckBox;
    PlanetMode: TRadioGroup;
    PlanetBox2: TCheckBox;
    PlanetBox3: TCheckBox;
    GRS: TFloatEdit;
    BitBtn37: TBitBtn;
    Edit2: TEdit;
    ComPageControl: TPageControl;
    comsetting: TTabSheet;
    GroupBox13: TGroupBox;
    Label154: TLabel;
    Label216: TLabel;
    Label231: TLabel;
    comlimitmag: TFloatEdit;
    showcom: TCheckBox;
    comsymbol: TRadioGroup;
    commagdiff: TFloatEdit;
    comdbset: TButton;
    comload: TTabSheet;
    Label232: TLabel;
    GroupBox14: TGroupBox;
    Label233: TLabel;
    comfile: TEdit;
    Loadcom: TButton;
    comfilebtn: TBitBtn;
    MemoCom: TMemo;
    comdelete: TTabSheet;
    Label238: TLabel;
    GroupBox16: TGroupBox;
    comelemlist: TComboBox;
    DelCom: TButton;
    GroupBox17: TGroupBox;
    Label239: TLabel;
    DelComAll: TButton;
    DelComMemo: TMemo;
    Addsinglecom: TTabSheet;
    Label241: TLabel;
    Label242: TLabel;
    Label243: TLabel;
    Label244: TLabel;
    Label245: TLabel;
    Label246: TLabel;
    Label247: TLabel;
    Label248: TLabel;
    Label249: TLabel;
    Label250: TLabel;
    Label251: TLabel;
    Label253: TLabel;
    Label254: TLabel;
    comid: TEdit;
    comh: TEdit;
    comg: TEdit;
    comep: TEdit;
    comperi: TEdit;
    comnode: TEdit;
    comi: TEdit;
    comec: TEdit;
    comq: TEdit;
    comnam: TEdit;
    comeq: TEdit;
    AddCom: TButton;
    comt: TMaskEdit;
    AstPageControl: TPageControl;
    astsetting: TTabSheet;
    GroupBox9: TGroupBox;
    Label203: TLabel;
    Label212: TLabel;
    Label213: TLabel;
    astlimitmag: TFloatEdit;
    showast: TCheckBox;
    astsymbol: TRadioGroup;
    astmagdiff: TFloatEdit;
    astdbset: TButton;
    astload: TTabSheet;
    Label206: TLabel;
    GroupBox7: TGroupBox;
    Label204: TLabel;
    Label215: TLabel;
    mpcfile: TEdit;
    astnumbered: TCheckBox;
    LoadMPC: TButton;
    mpcfilebtn: TBitBtn;
    aststoperr: TCheckBox;
    astlimitbox: TCheckBox;
    astlimit: TLongEdit;
    MemoMPC: TMemo;
    astprepare: TTabSheet;
    Label210: TLabel;
    GroupBox8: TGroupBox;
    Label7: TLabel;
    Label207: TLabel;
    aststrtdate: TMaskEdit;
    AstCompute: TButton;
    astnummonth: TSpinEdit;
    prepastmemo: TMemo;
    astdelete: TTabSheet;
    Label211: TLabel;
    GroupBox10: TGroupBox;
    astelemlist: TComboBox;
    delast: TButton;
    GroupBox11: TGroupBox;
    Label209: TLabel;
    delallast: TButton;
    delastMemo: TMemo;
    GroupBox12: TGroupBox;
    Label214: TLabel;
    astdeldate: TMaskEdit;
    deldateast: TButton;
    AddsingleAst: TTabSheet;
    Label217: TLabel;
    Label218: TLabel;
    Label219: TLabel;
    Label220: TLabel;
    Label221: TLabel;
    Label222: TLabel;
    Label223: TLabel;
    Label224: TLabel;
    Label225: TLabel;
    Label226: TLabel;
    Label227: TLabel;
    Label228: TLabel;
    Label229: TLabel;
    Label230: TLabel;
    astid: TEdit;
    asth: TEdit;
    astg: TEdit;
    astep: TEdit;
    astma: TEdit;
    astperi: TEdit;
    astnode: TEdit;
    asti: TEdit;
    astec: TEdit;
    astax: TEdit;
    astref: TEdit;
    astnam: TEdit;
    asteq: TEdit;
    Addast: TButton;
    s_display: TTabSheet;
    pa_display: TPageControl;
    t_display: TTabSheet;
    t_font: TTabSheet;
    t_color: TTabSheet;
    t_skycolor: TTabSheet;
    t_nebcolor: TTabSheet;
    t_lines: TTabSheet;
    t_labels: TTabSheet;
    Label14: TLabel;
    stardisplay: TRadioGroup;
    nebuladisplay: TRadioGroup;
    Bevel10: TBevel;
    Label51: TLabel;
    Label121: TLabel;
    Label122: TLabel;
    Label123: TLabel;
    Label124: TLabel;
    Label125: TLabel;
    Label126: TLabel;
    Label127: TLabel;
    Label128: TLabel;
    Label129: TLabel;
    SpeedButton1: TSpeedButton;
    SpeedButton2: TSpeedButton;
    SpeedButton3: TSpeedButton;
    SpeedButton4: TSpeedButton;
    SpeedButton5: TSpeedButton;
    SpeedButton6: TSpeedButton;
    SpeedButton7: TSpeedButton;
    Label235: TLabel;
    gridfont: TEdit;
    labelfont: TEdit;
    legendfont: TEdit;
    statusfont: TEdit;
    listfont: TEdit;
    prtfont: TEdit;
    Button1: TButton;
    symbfont: TEdit;
    Label8: TLabel;
    Label181: TLabel;
    Label182: TLabel;
    Label183: TLabel;
    Label184: TLabel;
    Label185: TLabel;
    Label186: TLabel;
    Label187: TLabel;
    Label188: TLabel;
    Label189: TLabel;
    Label190: TLabel;
    Label191: TLabel;
    Label192: TLabel;
    Label193: TLabel;
    Label194: TLabel;
    Label195: TLabel;
    Label197: TLabel;
    Label198: TLabel;
    Label199: TLabel;
    Label196: TLabel;
    Label11: TLabel;
    Label6: TLabel;
    Label234: TLabel;
    bg1: TPanel;
    Shape1: TShape;
    Shape2: TShape;
    Shape3: TShape;
    Shape4: TShape;
    Shape5: TShape;
    Shape6: TShape;
    Shape7: TShape;
    bg2: TPanel;
    Shape8: TShape;
    Shape9: TShape;
    Shape10: TShape;
    Shape11: TShape;
    Shape12: TShape;
    Shape13: TShape;
    bg3: TPanel;
    Shape15: TShape;
    Shape16: TShape;
    Shape17: TShape;
    Shape14: TShape;
    Shape25: TShape;
    DefColor: TRadioGroup;
    bg4: TPanel;
    Shape26: TShape;
    Shape27: TShape;
    Label200: TLabel;
    Label202: TLabel;
    Label205: TLabel;
    Label208: TLabel;
    skycolorbox: TRadioGroup;
    Panel6: TPanel;
    Shape18: TShape;
    Shape19: TShape;
    Shape20: TShape;
    Shape21: TShape;
    Shape22: TShape;
    Shape23: TShape;
    Shape24: TShape;
    Button3: TButton;
    Label201: TLabel;
    Label9: TLabel;
    Bevel6: TBevel;
    Label132: TLabel;
    Bevel11: TBevel;
    Label72: TLabel;
    Bevel12: TBevel;
    EqGrid: TCheckBox;
    CGrid: TCheckBox;
    Constl: TCheckBox;
    ConstlFile: TEdit;
    ConstlFileBtn: TBitBtn;
    ecliptic: TCheckBox;
    galactic: TCheckBox;
    Constb: TCheckBox;
    ConstbFile: TEdit;
    ConstbfileBtn: TBitBtn;
    milkyway: TCheckBox;
    fillmilkyway: TCheckBox;
    GridNum: TCheckBox;
    Label10: TLabel;
    labelcolorStar: TShape;
    Label236: TLabel;
    Label237: TLabel;
    Label240: TLabel;
    Label252: TLabel;
    Label255: TLabel;
    labelcolorVar: TShape;
    labelcolorMult: TShape;
    labelcolorNeb: TShape;
    labelcolorSol: TShape;
    labelcolorMisc: TShape;
    labelcolorConst: TShape;
    labelsizeStar: TSpinEdit;
    labelmagStar: TSpinEdit;
    showlabelStar: TCheckBox;
    labelsizeVar: TSpinEdit;
    labelmagVar: TSpinEdit;
    showlabelVar: TCheckBox;
    labelsizeMult: TSpinEdit;
    LabelmagMult: TSpinEdit;
    showlabelMult: TCheckBox;
    labelsizeNeb: TSpinEdit;
    labelmagNeb: TSpinEdit;
    showlabelNeb: TCheckBox;
    labelsizeSol: TSpinEdit;
    labelmagSol: TSpinEdit;
    showlabelSol: TCheckBox;
    labelsizeMisc: TSpinEdit;
    showlabelMisc: TCheckBox;
    showlabelConst: TCheckBox;
    labelsizeConst: TSpinEdit;
    MagLabel: TRadioGroup;
    constlabel: TRadioGroup;
    s_images: TTabSheet;
    s_system: TTabSheet;
    pa_images: TPageControl;
    t_images: TTabSheet;
    Label50: TLabel;
    pa_system: TPageControl;
    t_system: TTabSheet;
    t_server: TTabSheet;
    Label153: TLabel;
    GroupBox6: TGroupBox;
    Label77: TLabel;
    Label84: TLabel;
    Label85: TLabel;
    Label86: TLabel;
    Label133: TLabel;
    dbname: TEdit;
    dbport: TLongEdit;
    dbhost: TEdit;
    dbuser: TEdit;
    dbpass: TEdit;
    chkdb: TButton;
    credb: TButton;
    dropdb: TButton;
    AstDB: TButton;
    CometDB: TButton;
    GroupBox3: TGroupBox;
    Label54: TLabel;
    Label55: TLabel;
    UseIPserver: TCheckBox;
    ipaddr: TEdit;
    ipport: TEdit;
    keepalive: TCheckBox;
    GroupBox4: TGroupBox;
    ipstatus: TEdit;
    refreshIP: TButton;
    t_telescope: TTabSheet;
    Label13: TLabel;
    INDI: TGroupBox;
    Label75: TLabel;
    IndiServerHost: TEdit;
    Label130: TLabel;
    IndiServerPort: TEdit;
    IndiAutostart: TCheckBox;
    Label258: TLabel;
    IndiServerCmd: TEdit;
    Label259: TLabel;
    IndiDriver: TEdit;
    IndiDev: TComboBox;
    Label260: TLabel;
    Label261: TLabel;
    t_circle: TTabSheet;
    t_rectangle: TTabSheet;
    cb1: TCheckBox;
    cb2: TCheckBox;
    cb3: TCheckBox;
    cb4: TCheckBox;
    cb5: TCheckBox;
    cb6: TCheckBox;
    cb7: TCheckBox;
    cb8: TCheckBox;
    cb9: TCheckBox;
    cb10: TCheckBox;
    Label307: TLabel;
    Circlegrid: TStringGrid;
    CenterMark1: TCheckBox;
    rb1: TCheckBox;
    rb2: TCheckBox;
    rb3: TCheckBox;
    rb4: TCheckBox;
    rb5: TCheckBox;
    rb6: TCheckBox;
    rb7: TCheckBox;
    rb8: TCheckBox;
    rb9: TCheckBox;
    rb10: TCheckBox;
    Label308: TLabel;
    RectangleGrid: TStringGrid;
    CenterMark2: TCheckBox;
    IndiPort: TComboBox;
    TelescopeSelect: TRadioGroup;
    TelescopePlugin: TGroupBox;
    telescopepluginlist: TComboBox;
    Label155: TLabel;
    GroupBoxDir: TGroupBox;
    Label156: TLabel;
    prgdir: TEdit;
    Label157: TLabel;
    persdir: TEdit;
    BitBtn1: TBitBtn;
    BitBtn2: TBitBtn;
    starvisual: TGroupBox;
    StarSizeBar: TTrackBar;
    StarContrastBar: TTrackBar;
    SaturationBar: TTrackBar;
    Label256: TLabel;
    Label262: TLabel;
    Label263: TLabel;
    Label257: TLabel;
    SizeContrastBar: TTrackBar;
    StarButton1: TButton;
    StarButton2: TButton;
    StarButton3: TButton;
    StarButton4: TButton;
    imgpath: TEdit;
    BitBtn3: TBitBtn;
    Label264: TLabel;
    ScanImages: TButton;
    Label265: TLabel;
    nimages: TLabel;
    Label267: TLabel;
    Panel11: TPanel;
    ImgLumBar: TTrackBar;
    ImgContrastBar: TTrackBar;
    Label266: TLabel;
    Label268: TLabel;
    ProgressPanel: TPanel;
    ProgressCat: TLabel;
    ProgressBar1: TProgressBar;
    ShowImagesBox: TCheckBox;
    Shape28: TShape;
    Label269: TLabel;
    t_background: TTabSheet;
    Label270: TLabel;
    Label271: TLabel;
    backimg: TEdit;
    BitBtn5: TBitBtn;
    ShowBackImg: TCheckBox;
    backimginfo: TLabel;
    procedure TreeView1Change(Sender: TObject; Node: TTreeNode);
    procedure FormCreate(Sender: TObject);
    procedure SelectFontClick(Sender: TObject);
    procedure DefaultFontClick(Sender: TObject);
    procedure FormShow(Sender: TObject);
    procedure FWChange(Sender: TObject);
    procedure CDCStarSelClick(Sender: TObject);
    procedure CDCStarField1Change(Sender: TObject);
    procedure CDCStarField2Change(Sender: TObject);
    procedure CDCStarPathChange(Sender: TObject);
    procedure CDCStarSelPathClick(Sender: TObject);
    procedure StarBoxClick(Sender: TObject);
    procedure StarAutoBoxClick(Sender: TObject);
    procedure NebBoxClick(Sender: TObject);
    procedure BigNebBoxClick(Sender: TObject);
    procedure fsmagvisChange(Sender: TObject);
    procedure fsmagChange(Sender: TObject);
    procedure fmagChange(Sender: TObject);
    procedure fdimChange(Sender: TObject);
    procedure CDCNebSelPathClick(Sender: TObject);
    procedure CDCNebSelClick(Sender: TObject);
    procedure CDCNebField1Change(Sender: TObject);
    procedure CDCNebField2Change(Sender: TObject);
    procedure CDCNebPathChange(Sender: TObject);
    procedure USNBrightClick(Sender: TObject);
    procedure IRVarClick(Sender: TObject);
    procedure GCVBoxClick(Sender: TObject);
    procedure Fgcv1Change(Sender: TObject);
    procedure Fgcv2Change(Sender: TObject);
    procedure WDSboxClick(Sender: TObject);
    procedure Fwds1Change(Sender: TObject);
    procedure Fwds2Change(Sender: TObject);
    procedure gcv3Change(Sender: TObject);
    procedure wds3Change(Sender: TObject);
    procedure BitBtn14Click(Sender: TObject);
    procedure BitBtn15Click(Sender: TObject);
    procedure stardisplayClick(Sender: TObject);
    procedure nebuladisplayClick(Sender: TObject);
    procedure StringGrid3DrawCell(Sender: TObject; ACol, ARow: Integer;
      Rect: TRect; State: TGridDrawState);
    procedure StringGrid3MouseUp(Sender: TObject; Button: TMouseButton;
      Shift: TShiftState; X, Y: Integer);
    procedure StringGrid3SelectCell(Sender: TObject; ACol, ARow: Integer;
      var CanSelect: Boolean);
    procedure addcatClick(Sender: TObject);
    procedure delcatClick(Sender: TObject);
    procedure FormClose(Sender: TObject; var Action: TCloseAction);
    procedure fBigNebLimitChange(Sender: TObject);
    procedure equinoxtypeClick(Sender: TObject);
    procedure equinox1Change(Sender: TObject);
    procedure equinox2Change(Sender: TObject);
    procedure CheckBox1Click(Sender: TObject);
    procedure CheckBox2Click(Sender: TObject);
    procedure LongEdit2Change(Sender: TObject);
    procedure tzChange(Sender: TObject);
    procedure CheckBox4Click(Sender: TObject);
    procedure dt_utChange(Sender: TObject);
    procedure BitBtn4Click(Sender: TObject);
    procedure PMBoxClick(Sender: TObject);
    procedure DrawPmBoxClick(Sender: TObject);
    procedure lDrawPMyChange(Sender: TObject);
    procedure nextClick(Sender: TObject);
    procedure previousClick(Sender: TObject);
    procedure ProjectionChange(Sender: TObject);
    procedure StringGrid3SetEditText(Sender: TObject; ACol, ARow: Integer;
      const Value: WideString);
    procedure StringGrid3SetEditText2(Sender: TObject; ACol, ARow: Integer;
      const Value: String);
    procedure DateChange(Sender: TObject; NewValue: Integer);
    procedure DateChange2(Sender: TObject);
    procedure TimeChange(Sender: TObject; NewValue: Integer);
    procedure TimeChange2(Sender: TObject);
    procedure DegSpacingChange(Sender: TObject);
    procedure HourSpacingChange(Sender: TObject);
    procedure SimObjClickCheck(Sender: TObject);
    procedure stepunitClick(Sender: TObject);
    procedure stepsizeChange(Sender: TObject);
    procedure PlaParalaxeClick(Sender: TObject);
    procedure PlanetBoxClick(Sender: TObject);
    procedure PlanetModeClick(Sender: TObject);
    procedure GRSChange(Sender: TObject);
    procedure PlanetBox2Click(Sender: TObject);
    procedure PlanetBox3Click(Sender: TObject);
    procedure ApplyClick(Sender: TObject);
    procedure nbstepChange(Sender: TObject);
    procedure steplineClick(Sender: TObject);
    procedure bgClick(Sender: TObject);
    procedure ShapeMouseUp(Sender: TObject; Button: TMouseButton;
      Shift: TShiftState; X, Y: Integer);
    procedure DefColorClick(Sender: TObject);
    procedure skycolorboxClick(Sender: TObject);
    procedure ShapeSkyMouseUp(Sender: TObject; Button: TMouseButton;
      Shift: TShiftState; X, Y: Integer);
    procedure Button3Click(Sender: TObject);
    procedure EqGridClick(Sender: TObject);
    procedure CGridClick(Sender: TObject);
    procedure ConstlClick(Sender: TObject);
    procedure ConstlFileChange(Sender: TObject);
    procedure ConstlFileBtnClick(Sender: TObject);
    procedure ApparentTypeClick(Sender: TObject);
    procedure projectiontypeClick(Sender: TObject);
    procedure UseIPserverClick(Sender: TObject);
    procedure keepaliveClick(Sender: TObject);
    procedure ipaddrChange(Sender: TObject);
    procedure ipportChange(Sender: TObject);
    procedure refreshIPClick(Sender: TObject);
    procedure latdegChange(Sender: TObject);
    procedure longdegChange(Sender: TObject);
    procedure altmeterChange(Sender: TObject);
    procedure pressureChange(Sender: TObject);
    procedure temperatureChange(Sender: TObject);
    procedure ZoomImage1MouseUp(Sender: TObject; Button: TMouseButton;
      Shift: TShiftState; X, Y: Integer);
    procedure ZoomImage1Paint(Sender: TObject);
    procedure ZoomImage1PosChange(Sender: TObject);
    procedure HScrollBarChange(Sender: TObject);
    procedure VScrollBarChange(Sender: TObject);
    procedure ObszpClick(Sender: TObject);
    procedure ObszmClick(Sender: TObject);
    procedure ObsmapClick(Sender: TObject);
    procedure eclipticClick(Sender: TObject);
    procedure galacticClick(Sender: TObject);
    procedure ConstbClick(Sender: TObject);
    procedure ConstbFileChange(Sender: TObject);
    procedure ConstbfileBtnClick(Sender: TObject);
    procedure milkywayClick(Sender: TObject);
    procedure fillmilkywayClick(Sender: TObject);
    procedure PageControl1Change(Sender: TObject);
    procedure GridNumClick(Sender: TObject);
    procedure countrylistClick(Sender: TObject);
    procedure obsnameMouseEnter(Sender: TObject);
    procedure UpdCityList(changecity:boolean);
    procedure citylistChange(Sender: TObject);
    procedure citylistClick(Sender: TObject);
    procedure citysearchClick(Sender: TObject);
    procedure newcityClick(Sender: TObject);
    procedure updcityClick(Sender: TObject);
    procedure delcityClick(Sender: TObject);
    procedure horizonopaqueClick(Sender: TObject);
    procedure horizonfileChange(Sender: TObject);
    procedure horizonfileBtnClick(Sender: TObject);
    procedure liststarClick(Sender: TObject);
    procedure listnebClick(Sender: TObject);
    procedure listplaClick(Sender: TObject);
    procedure listvarClick(Sender: TObject);
    procedure listdblClick(Sender: TObject);
    procedure dbnameChange(Sender: TObject);
    procedure dbuserChange(Sender: TObject);
    procedure dbhostChange(Sender: TObject);
    procedure dbpassChange(Sender: TObject);
    procedure dbportChange(Sender: TObject);
    procedure chkdbClick(Sender: TObject);
    procedure credbClick(Sender: TObject);
    procedure dropdbClick(Sender: TObject);
    procedure AstDBClick(Sender: TObject);
    procedure showastClick(Sender: TObject);
    procedure astsymbolClick(Sender: TObject);
    procedure astlimitmagChange(Sender: TObject);
    procedure astmagdiffChange(Sender: TObject);
    procedure astdbsetClick(Sender: TObject);
    procedure mpcfilebtnClick(Sender: TObject);
    procedure LoadMPCClick(Sender: TObject);
    procedure AstComputeClick(Sender: TObject);
    procedure delastClick(Sender: TObject);
    procedure deldateastClick(Sender: TObject);
    procedure delallastClick(Sender: TObject);
    procedure stepresetClick(Sender: TObject);
    procedure AddastClick(Sender: TObject);
    procedure showcomClick(Sender: TObject);
    procedure comsymbolClick(Sender: TObject);
    procedure comlimitmagChange(Sender: TObject);
    procedure commagdiffChange(Sender: TObject);
    procedure comfilebtnClick(Sender: TObject);
    procedure LoadcomClick(Sender: TObject);
    procedure DelComClick(Sender: TObject);
    procedure DelComAllClick(Sender: TObject);
    procedure AddComClick(Sender: TObject);
    procedure planetdirChange(Sender: TObject);
    procedure planetdirselClick(Sender: TObject);
    procedure CometDBClick(Sender: TObject);
    procedure showlabelClick(Sender: TObject);
    procedure labelmagChange(Sender: TObject);
    procedure labelcolorMouseUp(Sender: TObject; Button: TMouseButton;
      Shift: TShiftState; X, Y: Integer);
    procedure labelsizeChange(Sender: TObject);
    procedure MagLabelClick(Sender: TObject);
    procedure constlabelClick(Sender: TObject);
    procedure IndiServerHostChange(Sender: TObject);
    procedure IndiServerPortChange(Sender: TObject);
    procedure IndiAutostartClick(Sender: TObject);
    procedure IndiServerCmdChange(Sender: TObject);
    procedure IndiDriverChange(Sender: TObject);
    procedure IndiPortChange(Sender: TObject);
    procedure IndiDevChange(Sender: TObject);
    procedure cb1Click(Sender: TObject);
    procedure CenterMark1Click(Sender: TObject);
    procedure CirclegridSetEditText(Sender: TObject; ACol, ARow: Integer;
      const Value: String);
    procedure rb1Click(Sender: TObject);
    procedure RectangleGridSetEditText(Sender: TObject; ACol,
      ARow: Integer; const Value: String);
    procedure TelescopeSelectClick(Sender: TObject);
    procedure telescopepluginlistChange(Sender: TObject);
    procedure BitBtn1Click(Sender: TObject);
    procedure BitBtn2Click(Sender: TObject);
    procedure StarSizeBarChange(Sender: TObject);
    procedure StarContrastBarChange(Sender: TObject);
    procedure SaturationBarChange(Sender: TObject);
    procedure SizeContrastBarChange(Sender: TObject);
    procedure StarButton1Click(Sender: TObject);
    procedure StarButton2Click(Sender: TObject);
    procedure StarButton3Click(Sender: TObject);
    procedure StarButton4Click(Sender: TObject);
    procedure BitBtn3Click(Sender: TObject);
    procedure ScanImagesClick(Sender: TObject);
    procedure imgpathChange(Sender: TObject);
    procedure ImgLumBarChange(Sender: TObject);
    procedure ImgContrastBarChange(Sender: TObject);
    procedure ShowImagesBoxClick(Sender: TObject);
    procedure backimgChange(Sender: TObject);
    procedure ShowBackImgClick(Sender: TObject);
    procedure BitBtn5Click(Sender: TObject);
  private
    { Déclarations privées }
    db:TmyDB;
    ObsMapFile:string;
    locktree:boolean;
    FFits: TFits;
    procedure EditGCatPath(row : integer);
    procedure DeleteGCatRow(p : integer);
  public
    { Déclarations publiques }
    ccat : conf_catalog;
    cshr : conf_shared;
    csc  : conf_skychart;
    cplot : conf_plot;
    cmain : conf_main;
    catalogempty: boolean;
    EarthMapZoom: double;
    Obsposx,Obsposy : integer;
    scrollw, scrollh : integer;
    scrolllock,obslock:boolean;
    compage,astpage,dbpage:integer;
    procedure SetLang(lang:string);
    procedure SetFonts(ctrl:Tedit;num:integer);
    procedure ShowTime;
    procedure ShowChart;
    procedure SetEquinox;
    procedure ShowDisplay;
    procedure ShowFonts;
    procedure ShowField;
    procedure SetFieldHint(var lab:Tlabel; n:integer);
    procedure ShowProjection;
    procedure ShowFilter;
    procedure ShowGridSpacing;
    procedure ShowGcat;
    procedure ShowCDCStar;
    procedure ShowCDCNeb;
    procedure ShowPlanet;
    procedure ShowLine;
    procedure ShowColor;
    procedure ShowSkyColor;
    procedure ShowServer;
    procedure ShowObservatory;
    Procedure SetScrollBar;
    Procedure SetObsPos;
    Procedure ShowObsCoord;
    procedure CenterObs;
    procedure ShowHorizon;
    procedure ShowObjList;
    procedure ShowImages;
    procedure CountImages;
    procedure ShowSYS;
    procedure ShowAsteroid;
    procedure UpdAstList;
    procedure ShowComet;
    procedure UpdComList;
    procedure showlabelcolor;
    procedure showlabel;
    procedure showcircle;
    procedure showrectangle;
    procedure showtelescope;
    property Fits: TFits read FFits write FFits;
  end;

var
  f_config: Tf_config;

implementation

uses pu_main; //todo: replace by event

const b=' ';

var
   SetDirectory : function(dir:pchar): integer; stdcall;
   ReadCountryFile: function (country:pchar; var City: PCities; var cfile:array of char): integer; stdcall;
   AddCity: function(City: PCity): integer; stdcall;
   ModifyCity: function(index: integer; City: PCity): integer; stdcall;
   RemoveCity: function(index: integer; City: PCity): integer; stdcall;
   ReleaseCities: function(): integer; stdcall;
   SearchCity: function(str: pchar): integer; stdcall;
   libCities : THandle;

var c : Pcities;
    total,first: integer;
    actual_country: string;
    autoprocess: boolean;

{$R *.dfm}

// include all cross-platform common code.
// you can temporarily copy the file content here
// to use the IDE facilities

{$include i_config.pas }

// end of common code

// windows vcl specific code:

procedure Tf_config.StringGrid3SetEditText2(Sender: TObject; ACol,
  ARow: Integer; const Value: String);
begin
  // clx compatibility call
  StringGrid3SetEditText(Sender,ACol,ARow,Value);
end;

procedure Tf_config.stepsizeChange(Sender: TObject);
begin
stepunitClick(Sender);
end;

procedure Tf_config.nbstepChange(Sender: TObject);
begin
csc.Simnb:=nbstep.value;
end;

procedure Tf_config.TelescopeSelectClick(Sender: TObject);
begin
csc.IndiTelescope:=Telescopeselect.itemindex=0;
INDI.visible:=csc.IndiTelescope;
TelescopePlugin.visible:=not csc.IndiTelescope;
end;

procedure Tf_config.telescopepluginlistChange(Sender: TObject);
begin
csc.ScopePlugin:=telescopepluginlist.text;
end;

// end of windows vcl specific code:

end.




