#!/bin/bash
#
# Script to start Cartes du Ciel on Linux.
# It MUST reside on the same directory as 
# all the excutable files and library.

# get current script directory
cname=$(echo $0 | sed 's/.*\///')
cpath=$(echo $0 | sed 's/'$cname'$//')

# add current directory to library search path
if [ -n "$LD_LIBRARY_PATH" ]; then
  export LD_LIBRARY_PATH="$cpath:$LD_LIBRARY_PATH"
else
  export LD_LIBRARY_PATH="$cpath"
fi

# use borland QT or own QT 
if [ ! -e $cpath"libborqt-6.9-qt2.3.so" ]; then
  echo
  echo "No soft link libborqt-6.9-qt2.3.so to libborqt-6.9.0-qt2.3.so found."
  echo
  echo "You must have a soft link libborqt-6.9-qt2.3.so"
  echo "somewhere in your library search path."
  echo
fi

# a LANG environment variable is require
if [ -z "$LANG" ]; then
  export LANG=en_US
fi

# run CDC
cd $cpath
$cpath"cdc_clx" -ns $*

